import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c3c8c1",
        "inverse-on-surface": "#f2f1e4",
        "secondary-fixed": "#b1f1c9",
        "on-tertiary-fixed": "#410003",
        "on-background": "#1b1c14",
        "on-secondary-fixed-variant": "#115134",
        "tertiary": "#110000",
        "on-primary-fixed-variant": "#434843",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1a1f1b",
        "surface-bright": "#fbfaec",
        "surface-dim": "#dbdbce",
        "on-error-container": "#93000a",
        "outline": "#747874",
        "surface-container-low": "#f5f4e7",
        "on-secondary-container": "#347050",
        "surface-variant": "#e3e3d6",
        "surface-container-high": "#e9e9db",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5a605b",
        "on-tertiary-container": "#dd5c53",
        "secondary": "#2e694a",
        "on-secondary-fixed": "#002111",
        "surface": "#fbfaec",
        "surface-container-highest": "#e3e3d6",
        "error": "#ba1a1a",
        "outline-variant": "#c4c7c2",
        "on-primary-container": "#828781",
        "on-primary": "#ffffff",
        "inverse-surface": "#303128",
        "on-tertiary-fixed-variant": "#881d1b",
        "primary": "#1A1F1B",
        "secondary-fixed-dim": "#96d4ae",
        "tertiary-fixed-dim": "#ffb4ac",
        "on-error": "#ffffff",
        "tertiary-container": "#450003",
        "primary-fixed": "#dfe4dd",
        "surface-container": "#efefe1",
        "background": "#EAEAE2",
        "secondary-container": "#b1f1c9",
        "on-surface": "#1b1c14",
        "on-surface-variant": "#55584F",
        "inverse-primary": "#c3c8c1",
        "on-primary-fixed": "#181d19",
        "tertiary-fixed": "#ffdad6",
        "surface-card": "#F6F6F1",
        "hairline": "#CFCFC2",
        "forest-green": "#1F5C3E",
        "deep-red": "#A3312C"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "grid-margin": "2rem",
        "cell-padding-v": "1rem",
        "gutter": "1px",
        "cell-padding-h": "1.5rem",
        "stack-gap": "2rem",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)"],
        "data-md": ["var(--font-jetbrains-mono)"],
        "headline-lg": ["var(--font-space-grotesk)"],
        "headline-xl": ["var(--font-space-grotesk)"],
        "label-sm": ["var(--font-jetbrains-mono)"],
        "body-lg": ["var(--font-inter)"],
        "data-lg": ["var(--font-jetbrains-mono)"],
        "headline-md": ["var(--font-space-grotesk)"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "data-lg": ["20px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "30px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
